### ISSUE TITLE
make error at the top

### ISSUE THREAD

**Issue by zone-min** [ZipCPU/dbgbus#4]
I get the following error when running make at the top level of dbgbus ,and 

verilator -Wall --MMD -trace -y ../../hexbus/rtl --Mdir obj_dir -cc testbus.v
make --no-print-directory -C obj_dir/ -f Vtestbus.mk
/usr/bin/perl /home/zone/Downloads/verilator/bin/verilator_includer -DVL_INCLUDE_OPT=include Vtestbus.cpp Vtestbus___024root__DepSet_h3d88c857__0.cpp Vtestbus___024root__DepSet_hbe927a50__0.cpp Vtestbus__Trace__0.cpp Vtestbus__ConstPool_0.cpp Vtestbus___024root__Slow.cpp Vtestbus___024root__DepSet_h3d88c857__0__Slow.cpp Vtestbus___024root__DepSet_hbe927a50__0__Slow.cpp Vtestbus__Syms.cpp Vtestbus__Trace__0__Slow.cpp > Vtestbus__ALL.cpp
ccache g++  -I.  -MMD -I/home/zone/Downloads/verilator/include -I/home/zone/Downloads/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=1 -faligned-new -fcf-protection=none -Wno-bool-operation -Wno-sign-compare -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -Wno-shadow      -std=gnu++14 -Os -c -o Vtestbus__ALL.o Vtestbus__ALL.cpp
echo "" > Vtestbus__ALL.verilator_deplist.tmp
Archive ar -rcs Vtestbus__ALL.a Vtestbus__ALL.o
rm Vtestbus__ALL.verilator_deplist.tmp
verilator -Wall --MMD -trace -y ../../hexbus/rtl --Mdir obj_dir -cc quikbus.v
make --no-print-directory -C obj_dir/ -f Vquikbus.mk
/usr/bin/perl /home/zone/Downloads/verilator/bin/verilator_includer -DVL_INCLUDE_OPT=include Vquikbus.cpp Vquikbus___024root__DepSet_h449c97b8__0.cpp Vquikbus___024root__DepSet_h451c77ba__0.cpp Vquikbus__Trace__0.cpp Vquikbus__ConstPool_0.cpp Vquikbus___024root__Slow.cpp Vquikbus___024root__DepSet_h449c97b8__0__Slow.cpp Vquikbus___024root__DepSet_h451c77ba__0__Slow.cpp Vquikbus__Syms.cpp Vquikbus__Trace__0__Slow.cpp > Vquikbus__ALL.cpp
ccache g++  -I.  -MMD -I/home/zone/Downloads/verilator/include -I/home/zone/Downloads/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=1 -faligned-new -fcf-protection=none -Wno-bool-operation -Wno-sign-compare -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -Wno-shadow      -std=gnu++14 -Os -c -o Vquikbus__ALL.o Vquikbus__ALL.cpp
echo "" > Vquikbus__ALL.verilator_deplist.tmp
Archive ar -rcs Vquikbus__ALL.a Vquikbus__ALL.o
rm Vquikbus__ALL.verilator_deplist.tmp
Building dependency file
g++ -Og -g -Wall -I/home/zone/Downloads/verilator/include -I../rtl/obj_dir -I../../sw/host -I../../sw -c testbus_tb.cpp -o obj-pc/testbus_tb.o
In file included from testbus_tb.cpp:50:
testb.h: In instantiation of ‘TESTB<VA>::TESTB() [with VA = Vtestbus]’:
testbus_tb.cpp:63:52:   required from here
testb.h:57:12: warning: ‘new’ of type ‘Vtestbus’ with extended alignment 64 [-Waligned-new=]
   57 |   m_core = new VA;
      |            ^~~~~~
testb.h:57:12: note: uses ‘void* operator new(std::size_t)’, which does not have an alignment parameter
testb.h:57:12: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
g++ -Og -g -Wall -I/home/zone/Downloads/verilator/include -I../rtl/obj_dir -I../../sw/host -I../../sw -c uartsim.cpp -o obj-pc/uartsim.o
g++ -Og -g -Wall -I/home/zone/Downloads/verilator/include -I../rtl/obj_dir -I../../sw/host -I../../sw -c /home/zone/Downloads/verilator/include/verilated.cpp -o obj-pc/verilated.o
g++ -Og -g -Wall -I/home/zone/Downloads/verilator/include -I../rtl/obj_dir -I../../sw/host -I../../sw -c /home/zone/Downloads/verilator/include/verilated_vcd_c.cpp -o obj-pc/verilated_vcd_c.o
g++ -Og -g -Wall -I/home/zone/Downloads/verilator/include -I../rtl/obj_dir -I../../sw/host -I../../sw obj-pc/testbus_tb.o obj-pc/uartsim.o obj-pc/verilated.o obj-pc/verilated_vcd_c.o ../rtl/obj_dir/Vtestbus__ALL.a -o testbus_tb
obj-pc/verilated.o: In function `VerilatedContext::threadPoolp()':
/home/zone/Downloads/verilator/include/verilated.cpp:2504: undefined reference to `VlThreadPool::VlThreadPool(VerilatedContext*, unsigned int)'
obj-pc/verilated_vcd_c.o: In function `std::thread::thread<void (VerilatedTrace<VerilatedVcd, VerilatedVcdBuffer>::*)(), VerilatedTrace<VerilatedVcd, VerilatedVcdBuffer>*, void>(void (VerilatedTrace<VerilatedVcd, VerilatedVcdBuffer>::*&&)(), VerilatedTrace<VerilatedVcd, VerilatedVcdBuffer>*&&)':
/usr/include/c++/9/thread:130: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
Makefile:105: recipe for target 'testbus_tb' failed
make[1]: *** [testbus_tb] Error 1
Makefile:83: recipe for target 'sim' failed
make: *** [sim] Error 2

**Comment by ZipCPU** [comment]
The problem traces to an update in Verilator that now requires all builds to include verilated_threads.cpp and -lpthread.  Should now be fixed.

**Comment by zone-min** [comment]
Thanks, I have already fixed that .

In addtion, I'm wondering if this dbgbus is similar to the functionality of vivado's ILA ?

Best Regards!

**Comment by ZipCPU** [comment]
It can be used as part of a replacement to Vivado's ILA, yes.  To do that, place a [WBSCOPE](https://github.com/ZipCPU/wbscope) on the bus for the debugging bus to access, and then you have something like ILA.  The trick is ... the bus has to work _perfectly_ for this to work.  As a bonus, you can also load RAM/FLASH, configure peripherals, experiment with your design, and more.  Indeed, I do this often when debugging items on an FPGA: 1) get the bus up and running, 2) measure what's going on within, 3) command a peripheral to do (something), 4) trigger a trace as that command runs, 5) go back and view the results of that trace, 6) ponder what just happened, 7) measure (again), and repeat.  I should point out, not only do I use the WBSCOPE, but I've often been known to bring various state bits back as well--just to make sure components of the design properly return to IDLE before issuing the next command.  (A classic component that might not?  I2C.  Make one little mistake, and ... the controller will need help resetting.)

**Comment by zone-min** [comment]
I got it, very appreciate for your patiently answer!
